services:
  mongo:
    image: mongo
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    ports:
      - 27017:27017
    command: mongod --quiet --logpath /dev/null 
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "80:80"
    depends_on:
      - mongo
